---

- name: install | install thoughtworks apt-repo
  apt_repository: 
   repo='deb {{gocd_server_apt_repo}} /'
   state=present

- name: install | apt install go-server
  apt: 
   pkg="go-server={{ gocd_server_version }}"
   state=present

- name: install | start go-server
  service: 
   name=go-server
   state=started
   enabled=yes
  notify:
     - wait_for_gocd_server