---

- name: install | install thoughtworks apt-repo
  apt_repository: 
   repo='deb {{gocd_server_apt_repo}} /'
   state=present
  register: thoughtworks_repo_install

- name: install | Update apt cache repo 
  apt:
    update_cache=yes
  when: thoughtworks_repo_install | changed

- name: install | apt install go-server latest available
  apt: 
   pkg="go-server"
   state="latest"
   force=yes
  when: gocd_server_version | lower == "latest"
  notify:
   - restart_gocd_server
  register: gocd_server_latest_install

- name: install | apt install go-server specific version
  apt: 
   pkg="go-server={{ gocd_server_version }}"
   state="present"
   force=yes
  when: gocd_server_version | lower != "latest"
  notify:
   - restart_gocd_server
  register: gocd_server_version_install

- name: install | go-server configuraiton file
  template: 
    src=go-server.j2
    dest="/etc/default/go-server"
    mode=0644
    group={{ gocd_server_group }}
    owner={{ gocd_server_user }}
  notify:
   - restart_gocd_server

- name: install | start go-server
  service: 
   name=go-server
   state=started
   enabled=yes
  notify:
     - wait_for_gocd_server
  when: not gocd_server_version_install | changed and not gocd_server_latest_install | changed 