---
- name: restart_gocd_server
  service: 
   name=go-server
   state=restart
   enabled=yes
  notify:
     - wait_for_gocd_server

- name: wait_for_gocd_server
  wait_for: 
    port="{{gocd_server_port}}"
    timeout="{{gocd_server_wait_for_timeout}}"
    delay=10
